name: RENACH_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6  
  - pip=19.1.1
  - numpy=1.17.4
  - pytesseract=0.3.1
  - poppler=0.84.0
  - tesseract=4.1.1
  - textdistance=4.1.3
  - pip:
    - opencv-contrib-python==4.1.2.30
    - mtcnn==0.1.0
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - pdf2image==1.11.0
    - tensorflow==1.15.0
    - tensorboard==1.15.0
    - tensorflow-estimator==1.15.1
    - h5py==2.10.0
    - mtcnn==0.1.0